-- DEVELOPMENT ONLY: Disable RLS on all tables
-- WARNING: Only use this in development environments!

-- Core tables
ALTER TABLE product_categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendors DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;

-- Configuration tables
ALTER TABLE paper_stocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE coatings DISABLE ROW LEVEL SECURITY;
ALTER TABLE turnaround_times DISABLE ROW LEVEL SECURITY;
ALTER TABLE print_sizes DISABLE ROW LEVEL SECURITY;
ALTER TABLE quantities DISABLE ROW LEVEL SECURITY;
ALTER TABLE sides DISABLE ROW LEVEL SECURITY;
ALTER TABLE add_ons DISABLE ROW LEVEL SECURITY;
ALTER TABLE add_on_sub_options DISABLE ROW LEVEL SECURITY;

-- Junction tables
ALTER TABLE product_paper_stocks DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_coatings DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_turnaround_times DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_print_sizes DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_quantities DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_sides DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_add_ons DISABLE ROW LEVEL SECURITY;

-- User and order related tables
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items DISABLE ROW LEVEL SECURITY;

-- CRM tables
ALTER TABLE crm_customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE crm_interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE crm_tasks DISABLE ROW LEVEL SECURITY;

-- Support tables
ALTER TABLE support_tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE support_messages DISABLE ROW LEVEL SECURITY;

-- Marketing tables
ALTER TABLE email_campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_recipients DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_templates DISABLE ROW LEVEL SECURITY;

-- File management
ALTER TABLE uploaded_files DISABLE ROW LEVEL SECURITY;

-- Verify RLS is disabled
SELECT 
    schemaname,
    tablename,
    rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;